### ISSUE TITLE
Specify intent of the site

### ISSUE THREAD

**Issue by scorchio** [phildini/stayinghomeclub#1190]
Hi -

I appreciate and like this initiative, but I can't say I fully understand it. I think it would make sense to specify what is the exact intent of compiling such a list and add it to the site and the README. How is this going to be used? Why would you recommend adding a company to the list?

**Comment by jenswegar** [comment]
Also, specifying if this is a list for only US related companies/events/schools or any part of the world would be useful.

**Comment by phildini** [comment]
Hey there. Thanks for filing an issue, I'm sorry to hear you're confused. Enough people have found this project useful (we have 1400+ PRs somehow, which I'm truly humbled by) that I don't think we need a ton more explanation.

If you look at what we're trying to do and can think of specific ways to improve our wording, PRs are gratefully accepted.
