### ISSUE TITLE
Current company list is not ordered by name

### ISSUE THREAD

**Issue by dankirkd** [phildini/stayinghomeclub#1213]
Would be nice to keep the list in some kind of order, but a number of entries are not.

**Comment by drewbrew** [comment]
It turns out this is because not all the files are in kebab-case. Some of them had leading capital letters. I fixed that in #1271.

Thanks!

**Comment by dankirkd** [comment]
@drewbrew Thanks.  I added a PR at https://github.com/phildini/stayinghomeclub/pull/1280 to update the wording in the README to that effect.  Please review and merge.
