### ISSUE TITLE
stanford

### ISSUE THREAD

**Issue by trafnar** [phildini/stayinghomeclub#129]
https://twitter.com/ericsson_axel/status/1236144774794493952

**Comment by phildini** [comment]
I'm not sure what to do with these... do I categorize stanford as a company? an event?

Do we need a separate category for Institutions?

**Comment by trafnar** [comment]
Schools or institutions category sounds like a good idea. List all the universities especially would be useful.

**Comment by phildini** [comment]
I would accept a PR that started that section as a table under Companies.`

**Comment by deargle** [comment]
See https://github.com/phildini/stayinghomeclub/pull/531, I'll add stanford so that this issue would be closed, too
