### ISSUE TITLE
Add algolia instant search

### ISSUE THREAD

**Issue by rajvijen** [phildini/stayinghomeclub#1320]

**Comment by rajvijen** [comment]
Add [algolia instant search](https://github.com/algolia/algoliasearch-client-ruby) for better user query.
Look at it - [Algolia is making its Pro Plan free to any developer or team working on COVID-19-related, not-for-profit websites or apps](https://blog.algolia.com/supporting-our-communities-during-this-time-of-need/)

Since this application will grow in the near future rapidly.

**Comment by phildini** [comment]
Hey I think this sounds pretty good but don't have the spoons to figure out how to make a static site parsed into Algolia. If you have thoughts there, I'd love to hear them.
