### ISSUE TITLE
Sources Formatting Suggestion

### ISSUE THREAD

**Issue by koronkowy** [phildini/stayinghomeclub#21]
Instead of having the sources be linked out on the company name, I believe it would make more sense to make another column and have Wikipedia-esque sources in the form of [1][2][3] etc.

It's inevitable that there will be several sources, especially with geo-specific WFH regulations.

**Comment by phildini** [comment]
@koronkowy I think that makes sense! I also don't really have the bandwidth to make that change myself. I would gratefully accept a PR doing so.

**Comment by koronkowy** [comment]
It looks like this has been implemented. Thanks, y'all!
