### ISSUE TITLE
Verizon Media

### ISSUE THREAD

**Issue by b0r3dguy** [phildini/stayinghomeclub#217]
Employees have been informed via email from our CEO that there are travel restrictions in place as well as restrictions on visitors & events. WFH is only required for the following offices: Hong Kong, Singapore, Japan and Italy.

All other Verizon Media offices are not required to work from home, yet.

**Comment by krishnatre-siddhartha** [comment]
Is this issue taken care of? If not, happy to do the code. Do let me know ASAP. :)

**Comment by b0r3dguy** [comment]
It's not taken care of yet, but I would like to add that the situation has changed further. It's not only Verizon Media, it's also for Verizon as well.

**Comment by krishnatre-siddhartha** [comment]
Thanks! Will make necessary updates.

**Comment by drewbrew** [comment]
Closing since #1344 is merged. Thanks!
