### ISSUE TITLE
SXSW

### ISSUE THREAD

**Issue by drewbrew** [phildini/stayinghomeclub#25]
How should this list handle companies pulling out of events that are still happening?

Apple, Facebook, Twitter, Amazon Studios, and Netflix have all pulled out of SXSW, but as of Monday, the event is still happening: https://www.theverge.com/2020/3/4/21165588/apple-pulling-out-sxsw-coronavirus-apple-tv-plus-austin

**Comment by koronkowy** [comment]
With the formatting I submitted with issue #41 and relative PR, it should now be easy to put SXSW as a sub sub sub sub class and then break out each company underneath. If/when that gets merged, I can try to tackle this.

**Comment by koronkowy** [comment]
This issue should be resolved as all of SXSW is now cancelled and has been added to the list.

**Comment by drewbrew** [comment]
Yep, closing this.
