### ISSUE TITLE
E3 is out

### ISSUE THREAD

**Issue by bbarhight** [phildini/stayinghomeclub#268]
https://e3expo.com/ 

| dates    | 9-11 June 2020|
|---|---|
| location | Los Angeles, California|
| Industry | Gaming|

NEWS: E3 2020 CANCELLED DUE TO GROWING CONCERNS OVER COVID-19 VIRUS
After careful consultation with our member companies regarding the health and safety of everyone in our industry – our fans, our employees, our exhibitors, and our longtime E3 partners – we have made the difficult decision to cancel E3 2020, scheduled for June 9-11 in Los Angeles.

Following increased and overwhelming concerns about the COVID-19 virus, we felt this was the best way to proceed during such an unprecedented global situation. We are very disappointed that we are unable to hold this event for our fans and supporters. But we know it’s the right decision based on the information we have today.

Our team will be reaching out directly to exhibitors and attendees with information about providing full refunds.

We are also exploring options with our members to coordinate an online experience to showcase industry announcements and news in June 2020. Updates will be shared on E3Expo.com.

We thank everyone who shared their views on reimagining E3 this year. We look forward to bringing you E3 2021 as a reimagined event that brings fans, media, and the industry together in a showcase that celebrates the global video game industry.

**Comment by trafnar** [comment]
this is in master already, but perhaps more details can be added

**Comment by bbarhight** [comment]
Nah, it includes a link. We're good.
