### ISSUE TITLE
Linaro Connect BUD20 rescheduled as online Linaro Tech Days

### ISSUE THREAD

**Issue by vielmetti** [phildini/stayinghomeclub#27]
See https://linarotechdays.sched.com/

Online session scheduling in progress for the week of March 23-27. This event is the 2x annual all-hands meeting for Linaro as well as a public conference focused on Arm developers.

**Comment by phildini** [comment]
Good info! PRs gratefully accepted.

**Comment by koronkowy** [comment]
Issue addressed by merged PR #54, advised to close issue.

**Comment by vielmetti** [comment]
Thank you @koronkowy @phildini ! closing as fixed.
