### ISSUE TITLE
WSLconf details

### ISSUE THREAD

**Issue by vielmetti** [phildini/stayinghomeclub#29]
WSLconf (added at https://github.com/phildini/stayinghomeclub/commit/90859313afd3159b1e22037976d785506ad4bae9 ) has this update:

Revised schedule is live:

https://twitter.com/unixterminal/status/1235569661556604931

dates Tuesday March 10, Wednesday March 11.

**Comment by phildini** [comment]
Good info! PRs gratefully accepted.

**Comment by vielmetti** [comment]
Thanks @phildini @koronkowy - closing as fixed.
