### ISSUE TITLE
How to access the public site code?

### ISSUE THREAD

**Issue by trafnar** [phildini/stayinghomeclub#33]
I'd like to contribute by working on the data and on the public site (https://stayinghome.club) is that a separate repo? I can't find the code for it.

**Comment by phildini** [comment]
Hey @trafnar! This site is run through [Github Pages](https://pages.github.com/), which uses [Jekyll](https://jekyllrb.com/) under the hood.

Any PRs about using a different theme or configuration gratefully accepted.

**Comment by trafnar** [comment]
Thanks
