### ISSUE TITLE
Small Indian company, taking precautions & asking all to WFH 

### ISSUE THREAD

**Issue by supreettare** [phildini/stayinghomeclub#438]
Hi, 
We are Taritas, a small IT company in central India. We too have asked for WFH as a precaution to everyone in the office who can. 
Stats: 55 people in total, 10 already wfh, remaining 45 Encouraged to WFH.

**Comment by krishnatre-siddhartha** [comment]
Will do it. Date effected?

**Comment by drewbrew** [comment]
Closing since #1225 is merged
