### ISSUE TITLE
Discussion: University file naming

### ISSUE THREAD

**Issue by drewbrew** [phildini/stayinghomeclub#666]
In the past 24 hours, we've had 3 different university PRs with the file names being an initialism for the university.

This isn't scalable (see discussion at https://github.com/phildini/stayinghomeclub/pull/662#discussion_r392178604 for an example).

@ableyjoe suggested using a reverse DNS naming to have a canonical means of avoiding conflicts.

What do you think, @phildini and @toothbrush (adding you since you're improving the readme)?

**Comment by toothbrush** [comment]
Thanks for giving me a heads up!  

What i said in that thread was:
>Tough call! If it were me, i wouldn't enforce too much, to keep people feeling there's a low barrier to contributing.
> 
> But for sure, consistency has the advantage that it's easier for folks to see if they're about to make a duplicate... Depends on whether you want more mental burden on the maintainers or the contributors!

I think at this point i'd pick the thing least likely to cause double work, so maybe adopt a stricter naming scheme going forward, but leave the previous ones?

**Comment by deargle** [comment]
I can rename all previous ones in one swoop, it won't affect the rendering. Filename is not relied on.

**Comment by deargle** [comment]
For NCAA purposes etc, unis already have unique abbreviations. There's only "one" ASU from the view of the uni. The domain name usually has the accepted abbreviation. Using this example, Arkansas State is astate, Alabama State is alasu. All domains will end with edu, so the standard could be to use the domain name. Except betimes there are other things more descriptive.

Shouldn't it be easy for contributors to look at the listing on the index.md and see which ones have already been done, regardless of file name? The uni names could be sorted alphabetically.

**Comment by deargle** [comment]
Oh duh, this is bigger than just the US. Hmm. I'm back to agreeing with your reverse-domain idea.

**Comment by ableyjoe** [comment]
On Mar 13, 2020, at 17:21, Dave Eargle <notifications@github.com> wrote:

> Oh duh, this is bigger than just the US. Hmm. I'm back to agreeing with your reverse-domain idea.

:-)
